### 넘파이(NumPy) : 배열(ndarray, n dimension array)
* 리스트(list) : Linked List구조(불연속), 동작 속도가 느리다, comma로 요소구별, 서로 다른 자료형 사용가능 
* 배열(ndarray) : 연속된 메모리 구조, 동작 속도가 빠르다, comma를 사용하지 않고 공백으로 요소 구별,오직 한 가지 타입만 갖을 수 있다 

In [2]:
import numpy as np         # numpy를 np로 부를게 !
a=np.array([0,1,2,3,4,5])   # .의 개념 : np 안에 array (전라남도. 여수시 ~~)
print(a)
print(type(a))
# 주로 숫자 배열에 많이 쓰임
print(a.dtype) #int32 = 32부터 정수입니다.
print(a.shape) #shape : (6,)

[0 1 2 3 4 5]
<class 'numpy.ndarray'>
int32
(6,)


In [3]:
b = [0,1,2,3,4,5] #list는 쉼표로 구분 / ndarray는 , 없음
print(type(b),b)

<class 'list'> [0, 1, 2, 3, 4, 5]


In [6]:
# numpy 의 dtype 객체의 종류: 대소문자 모두 사용가능
np.sctypeDict.keys()

dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 9, 'uintp', 'P', 10, 'long', 'l', 7, 'L', 8, 'longlong', 'q', 'ulonglong', 'Q', 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'b1', 'int64', 'i8', 'uint64', 'u8', 'float16', 'f2', 'float32', 'f4', 'float64', 'f8', 'complex64', 'c8', 'complex128', 'c16', 'object0', 'bytes0', 'str0', 'void0', 'datetime64', 'M8', 'timedelta64', 'm8', 'Bytes0', 'Datetime64', 'Str0', 'Uint64', 'int32', 'i4', 'uint32', 'u4', 'int16', 'i2', 'uint16', 'u2', 'int8', 'i1', 'uint8', 'u1', 'complex_', 'int0', 'uint0', 'single', 'csingle', 'singlecomplex', 'float_', 'intc', 'uintc', 'int_', 'longfloat', 'clongfloat', 'longcomplex', 'bool_', 'bytes_', 'string_', 'str_', 'unicode_', 'object_', 'int', 'float', 'complex', 'bool', 'ob

### 차원(dimension, Rank) 과 Shape

* 차원(Dimension, Rank) : 1,2,3 차원 , n 차원, 첫 데이터까지의 대괄호의 갯수
* Shape : 차원의 요소의 수, 튜플 형식
#### 1차원 Shape : (x,) 축이 0
#### 2차원 Shape : (x,y)  , 행렬(matrix)
#### 3차원 Shape : (x,y,z) , (면,행,열)
...
#### n차원 Shape : (x,y,z,....)

In [10]:
# 2차원 배열의 Shape : 행(↓row,가로,수직,axis = 0) 과 열(→column,세로,수평,axis =1)  ==> 필수 암기(직행버스)
m = np.array([[0,1,2],
              [0,1,2]])
print(m)
print(m.shape) #2행 3열

[[0 1 2]
 [0 1 2]]
(2, 3)


In [15]:
# 3차원 배열의 Shape : (면,행,열)
m = np.array([[[0,1,2],
               [3,4,5]],
              [[0,1,2],
               [3,4,5]]])
print(m)
print(m.shape) #바깥쪽부터 대괄호 갯수 세어가는 원리

m.reshape(1,2,2,3)
print(m)
m.reshape(1,2,2,3,1)

[[[0 1 2]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]]]
(2, 2, 3)
[[[0 1 2]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]]]


array([[[[[0],
          [1],
          [2]],

         [[3],
          [4],
          [5]]],


        [[[0],
          [1],
          [2]],

         [[3],
          [4],
          [5]]]]])

### 배열의 shape 바꾸기 : reshape() 함수

In [25]:
m1=np.arange(12)
print(m1)
print(m1.shape) #(12,) -->1차원

m2 = m1.reshape(3,4)  #-->2차원
print(m2,m2.shape)

m3=m1.reshape(3,2,2) #곱해서 12가 되면 다 된다 
print(m3)             #--> 3차원

m4 = m1.reshape(2,2,3,1) #--> 4차원
print(m4)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
[[[[ 0]
   [ 1]
   [ 2]]

  [[ 3]
   [ 4]
   [ 5]]]


 [[[ 6]
   [ 7]
   [ 8]]

  [[ 9]
   [10]
   [11]]]]


In [20]:
list(range(0,12,1))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [29]:
# -1을 사용한 reshape : 
m2=m1.reshape(4,-1)
print(m2, m2.shape) #자동으로 요소 갯수 계산

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] (4, 3)


In [30]:
#1차원으로 변경 flatten
m1 = m3.flatten()
print(m1.shape)

(12,)


도움말 단축키 : shift+Tab

### 배열의 인덱싱과 슬라이싱

In [50]:
# 2차원 배열의 인덱싱과 슬라이싱
# data[행, 열]
d= np.arange(12).reshape(3,4)
print(d,d.shape)

#인덱싱
print(d[0,0])
print(d[2,1])
print(d[-1,-1])

#슬라이싱 ***자주 쓰인다 ***
print(d[0:2])
print('')
print(d[:,:-1]) #(3,3) 마지막 열을 제외
print('')
print(d[:,1:]) #(3,3) 첫번째 열을 제외
print('')
#마지막 열만 추출
print(d[:,-1]) #1차원으로 변형되어 호출됨
print(d[:,-1:])
print(d[:,[-1]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
0
9
11
[[0 1 2 3]
 [4 5 6 7]]

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]

[ 3  7 11]
[[ 3]
 [ 7]
 [11]]
[[ 3]
 [ 7]
 [11]]


In [29]:
# 3차원 배열의 인덱싱과 슬라이싱
# data[면,행,열]
d= np.arange(12).reshape(2,2,3)
print(d,d.shape)
print("-")
# 인덱싱 : 요소 1개 꺼내기
print(d[0,1,2])
print("-")
#슬라이싱
print (d[:,:-1,:-1])
print("-")
print(d[:,1,1])
print('-')
print(d[:,:,-1]) #슬라이싱하는데 인덱싱(-1)을 넣으면 차원이 축소함

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)
-
5
-
[[[0 1]]

 [[6 7]]]
-
[ 4 10]
-
[[ 2  5]
 [ 8 11]]


In [30]:
# 인덱싱 결과는 scalar
# 슬라이싱 결과는 ndarray
a = np.arange(12)
print(a,a.shape)

print(a[0])    # 0, scalar
print(a[0:1])  # [0] , 배열(ndarray)
print(a[[0]])  # [0] ,동일한 결과

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
0
[0]
[0]


### 불린 인덱싱 : 조건식을 사용한 인덱싱, 조건 검색 필터를 사용한 추출(매우 중요)

In [44]:
a=np.array([1,2,3,4,5,6])
print(a)

print(a>2)
print(a[a>2]) #배열 a에서 2보다 큰 요소를 추출, 결과는 배열
print(a[[False,False,True,True,True,True]]) #동일한 결과
#배열의 장점 : 연속된 메모리 출력 가능, 반복문 없이 반복되는 과정 한 번에 실행가능

print(a+100) #리스트는 한 번에 계산이 안됨. 넘파이 array로만 됨.
print(a[a!=3]) 
print(a[(a>2 | (a<6))]) #or
print(a[(a>2 & (a<6))]) #and
print(a[a%2==0]) #2로 나눈 나머지가 0인 것=짝수를 추출

a.mean() #통계


[1 2 3 4 5 6]
[False False  True  True  True  True]
[3 4 5 6]
[3 4 5 6]
[101 102 103 104 105 106]
[1 2 4 5 6]
[4 5 6]
[1 2 3 4 5 6]
[2 4 6]


3.5

### 배열의 연산
### [1] 배열과 상수간의 연산 :배열 <연산자> 상수, 상수 <연산자> 배열
#### 하나의 스칼라와 배열의 연산, 브로드 캐스팅에 해당

In [52]:
A = np.arange(16).reshape(4,4)
print(A,A.shape)

print(A+10) #캐스팅 : 형변환 / shape을 broad하게 바꾼다 = 브로드캐스팅 , 상수일 때는 무조건 된다.
print(10+A)
print("")
print(10*A)
print(A/10)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] (4, 4)
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]

[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]
 [120 130 140 150]]
[[0.  0.1 0.2 0.3]
 [0.4 0.5 0.6 0.7]
 [0.8 0.9 1.  1.1]
 [1.2 1.3 1.4 1.5]]


In [53]:
print(np.divide(10,0)) # inf 무한대
print(np.divide(0,0)) # nan : not a number

inf
nan


C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_24876\891709269.py:1: RuntimeWarning: divide by zero encountered in true_divide
  print(np.divide(10,0)) # inf 무한대
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_24876\891709269.py:2: RuntimeWarning: invalid value encountered in true_divide
  print(np.divide(0,0)) # nan : not a number


### [2] 배열과 배열의  연산 
### (1) element-wise 연산 : 요소간의 연산

In [60]:
# shape이 같은 경우
A = np.arange(9).reshape(3,3)
print(A)
B = np.arange(9).reshape(3,3) -1 
print(B)

print(A+B) # 각 요소끼리 더해짐
print(A*B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[-1  1  3]
 [ 5  7  9]
 [11 13 15]]
[[ 0  0  2]
 [ 6 12 20]
 [30 42 56]]


In [63]:
# shape이 다른 경우
# 브로드캐스팅 : 차원이나 shape이 서로 다른 배열에서 산술 연산이 가능 (내부에서 shape이 맞춰짐)
A=np.arange(6).reshape(3,2)
B=np.arange(2).reshape(1,2)
print(A)
print(B)
print("-"*30)
print(A+B) #연산시 배열 B가 (3,2)로 일시적으로 자동 변경되어 연산

[[0 1]
 [2 3]
 [4 5]]
[[0 1]]
------------------------------
[[0 2]
 [2 4]
 [4 6]]


#### 브로드 캐스팅 규칙 : 차원과 shape 이 자동 조정
#### 규칙 1 : 두 배열의 차원 수가 다르면 더 작은 수의 차원을 가진 배열의 shape의 앞쪽(왼쪽)을 1로 채운다
#### 규칙 2 : 차원이 같은 두 배열의 shape 이 1인 배열을 다른 배열의 shape과 일치하도록 늘인다
#### 규칙 3 : 임의의 차원에서 크기가 일치하지 않고 1도 아니라면 오류가 발생

In [64]:
A=np.ones((2,3)) #(2,3), 2차원
B = np.arange(3) #(3, ), 1차원 
print(A)
print(B)
#규칙 1 적용 : B의 shape ==> (3) -> (1,3) , B[0 1 2] --> B[[0 1 2]]
#규칙 2 적용 : B의 shape ==> (1,3)  -> (2,3) , B : [[0 1 2]
#                                                  [0 1 2]]
print(A+B)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]]


In [ ]:
A=np.ones((3,2)) #(3,2), 2차원
B = np.arange(3) #(3, ), 1차원 
print(A)
print(B)

# 규칙 3에 해당되므로 오류 (크기 일치X, 1도 아님)

In [ ]:
# 끝쪽 차원부터 비교하면서 앞쪽으로 진행한다
# 두 배열의 각 차원에서 shape 이 같거나 shape이 1인경우 브로드캐스팅 가능
# A  =  (2, 3)
# B  =     (3,)
# ----------------
# 결과:  (2, 3)
    
# A  =  (3, 1)
# B  =     (3,)
# ----------------  
# 결과:  (3, 3) 1이 3으로 바뀜


# A  =  (3, 2)
# B  =     (3,)
# ---------------- 
# 결과:  (3, x) ==> 오류

# A  =  (15, 3, 5)
# B  =      (3, 1) 
# ---------------- 
# 결과: (15, 3, 5)   

# A  =  (8, 1, 6, 1)
# B  =     (7, 1, 5)
# --------------------
# 결과:  (8, 7, 6, 5)

# A  =  (8, 4, 3)
# B  =     (2, 1)
# ----------------
# 결과: (8, x, 3) ==> 오류 

### (2) dot product: 내적 곱셈 ,행렬(matrix)

In [66]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])
print(A)   # (2,3)
print(B)   # (3,2)

# print(A*B) #ValueError, element-wise 연산 불가 (브로드캐스팅 실패)

result = np.dot(A,B) # 행렬의 내적 곱셈
print(result)

# (2,3) * (3,2) = (2,2)
# (m,n) * (n,L) = (m,L) 행렬의 내적 곱셈 시 shape 공식 ==> 필수 암기 요망 !!

#(10,4) * (n,L) = (10,2) # n=4, L=2 를 구할 수 있어야 한다.
#  X    *   W   =  Y

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 58  64]
 [139 154]]


In [69]:
# <class 'numpy.matrix'>
A=np.mat("1 2 3 ; 4 5 6")
B=np.mat("7 8;9 10;11 12")

print(A)  #(2,3)
print(B)  #(3,2)
print(type(A))

print(A*B) # 행렬의 내적 곱셈 np.dot보다 훨씬 편리
print(A*B*A*B) #(2,3) * (3,2) --> (2,2)* A(2,3) --> (2,3)*B(3,2) -->(2,2)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
<class 'numpy.matrix'>
[[ 58  64]
 [139 154]]
[[12260 13568]
 [29468 32612]]
